// Generated by gencpp from file agv_mode_srvs/agv_mode_srvRequest.msg
// DO NOT EDIT!


#ifndef AGV_MODE_SRVS_MESSAGE_AGV_MODE_SRVREQUEST_H
#define AGV_MODE_SRVS_MESSAGE_AGV_MODE_SRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_mode_srvs
{
template <class ContainerAllocator>
struct agv_mode_srvRequest_
{
  typedef agv_mode_srvRequest_<ContainerAllocator> Type;

  agv_mode_srvRequest_()
    : mode(0)  {
    }
  agv_mode_srvRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef int64_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct agv_mode_srvRequest_

typedef ::agv_mode_srvs::agv_mode_srvRequest_<std::allocator<void> > agv_mode_srvRequest;

typedef boost::shared_ptr< ::agv_mode_srvs::agv_mode_srvRequest > agv_mode_srvRequestPtr;
typedef boost::shared_ptr< ::agv_mode_srvs::agv_mode_srvRequest const> agv_mode_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator1> & lhs, const ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator1> & lhs, const ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_mode_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "284404659b502753974e60f7457ed2dc";
  }

  static const char* value(const ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x284404659b502753ULL;
  static const uint64_t static_value2 = 0x974e60f7457ed2dcULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_mode_srvs/agv_mode_srvRequest";
  }

  static const char* value(const ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 mode\n"
;
  }

  static const char* value(const ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct agv_mode_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_mode_srvs::agv_mode_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MODE_SRVS_MESSAGE_AGV_MODE_SRVREQUEST_H
