// Generated by gencpp from file moobot_msgs/ultrasonic_status.msg
// DO NOT EDIT!


#ifndef MOOBOT_MSGS_MESSAGE_ULTRASONIC_STATUS_H
#define MOOBOT_MSGS_MESSAGE_ULTRASONIC_STATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moobot_msgs
{
template <class ContainerAllocator>
struct ultrasonic_status_
{
  typedef ultrasonic_status_<ContainerAllocator> Type;

  ultrasonic_status_()
    : S_Protection(false)  {
    }
  ultrasonic_status_(const ContainerAllocator& _alloc)
    : S_Protection(false)  {
  (void)_alloc;
    }



   typedef uint8_t _S_Protection_type;
  _S_Protection_type S_Protection;





  typedef boost::shared_ptr< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> const> ConstPtr;

}; // struct ultrasonic_status_

typedef ::moobot_msgs::ultrasonic_status_<std::allocator<void> > ultrasonic_status;

typedef boost::shared_ptr< ::moobot_msgs::ultrasonic_status > ultrasonic_statusPtr;
typedef boost::shared_ptr< ::moobot_msgs::ultrasonic_status const> ultrasonic_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moobot_msgs::ultrasonic_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moobot_msgs::ultrasonic_status_<ContainerAllocator1> & lhs, const ::moobot_msgs::ultrasonic_status_<ContainerAllocator2> & rhs)
{
  return lhs.S_Protection == rhs.S_Protection;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moobot_msgs::ultrasonic_status_<ContainerAllocator1> & lhs, const ::moobot_msgs::ultrasonic_status_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moobot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efb803211b7dc44878ac181a026e608e";
  }

  static const char* value(const ::moobot_msgs::ultrasonic_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefb803211b7dc448ULL;
  static const uint64_t static_value2 = 0x78ac181a026e608eULL;
};

template<class ContainerAllocator>
struct DataType< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moobot_msgs/ultrasonic_status";
  }

  static const char* value(const ::moobot_msgs::ultrasonic_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool S_Protection\n"
;
  }

  static const char* value(const ::moobot_msgs::ultrasonic_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.S_Protection);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultrasonic_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moobot_msgs::ultrasonic_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moobot_msgs::ultrasonic_status_<ContainerAllocator>& v)
  {
    s << indent << "S_Protection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.S_Protection);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOOBOT_MSGS_MESSAGE_ULTRASONIC_STATUS_H
