// Generated by gencpp from file agv_mode_srvs/agv_mode_srvResponse.msg
// DO NOT EDIT!


#ifndef AGV_MODE_SRVS_MESSAGE_AGV_MODE_SRVRESPONSE_H
#define AGV_MODE_SRVS_MESSAGE_AGV_MODE_SRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agv_mode_srvs
{
template <class ContainerAllocator>
struct agv_mode_srvResponse_
{
  typedef agv_mode_srvResponse_<ContainerAllocator> Type;

  agv_mode_srvResponse_()
    : newmode(0)  {
    }
  agv_mode_srvResponse_(const ContainerAllocator& _alloc)
    : newmode(0)  {
  (void)_alloc;
    }



   typedef int64_t _newmode_type;
  _newmode_type newmode;





  typedef boost::shared_ptr< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct agv_mode_srvResponse_

typedef ::agv_mode_srvs::agv_mode_srvResponse_<std::allocator<void> > agv_mode_srvResponse;

typedef boost::shared_ptr< ::agv_mode_srvs::agv_mode_srvResponse > agv_mode_srvResponsePtr;
typedef boost::shared_ptr< ::agv_mode_srvs::agv_mode_srvResponse const> agv_mode_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator1> & lhs, const ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.newmode == rhs.newmode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator1> & lhs, const ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agv_mode_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "961eb286071c8202bbb98ce138adb626";
  }

  static const char* value(const ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x961eb286071c8202ULL;
  static const uint64_t static_value2 = 0xbbb98ce138adb626ULL;
};

template<class ContainerAllocator>
struct DataType< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agv_mode_srvs/agv_mode_srvResponse";
  }

  static const char* value(const ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 newmode\n"
"\n"
;
  }

  static const char* value(const ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.newmode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct agv_mode_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agv_mode_srvs::agv_mode_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "newmode: ";
    Printer<int64_t>::stream(s, indent + "  ", v.newmode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGV_MODE_SRVS_MESSAGE_AGV_MODE_SRVRESPONSE_H
