// Generated by gencpp from file moobot_ui/waypoint.msg
// DO NOT EDIT!


#ifndef MOOBOT_UI_MESSAGE_WAYPOINT_H
#define MOOBOT_UI_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moobot_ui
{
template <class ContainerAllocator>
struct waypoint_
{
  typedef waypoint_<ContainerAllocator> Type;

  waypoint_()
    : way_point_name()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  waypoint_(const ContainerAllocator& _alloc)
    : way_point_name(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _way_point_name_type;
  _way_point_name_type way_point_name;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::moobot_ui::waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moobot_ui::waypoint_<ContainerAllocator> const> ConstPtr;

}; // struct waypoint_

typedef ::moobot_ui::waypoint_<std::allocator<void> > waypoint;

typedef boost::shared_ptr< ::moobot_ui::waypoint > waypointPtr;
typedef boost::shared_ptr< ::moobot_ui::waypoint const> waypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moobot_ui::waypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moobot_ui::waypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moobot_ui::waypoint_<ContainerAllocator1> & lhs, const ::moobot_ui::waypoint_<ContainerAllocator2> & rhs)
{
  return lhs.way_point_name == rhs.way_point_name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moobot_ui::waypoint_<ContainerAllocator1> & lhs, const ::moobot_ui::waypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moobot_ui

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moobot_ui::waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moobot_ui::waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moobot_ui::waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moobot_ui::waypoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moobot_ui::waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moobot_ui::waypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moobot_ui::waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a43892a9a5e3559df1641a6a9d36bbe8";
  }

  static const char* value(const ::moobot_ui::waypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa43892a9a5e3559dULL;
  static const uint64_t static_value2 = 0xf1641a6a9d36bbe8ULL;
};

template<class ContainerAllocator>
struct DataType< ::moobot_ui::waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moobot_ui/waypoint";
  }

  static const char* value(const ::moobot_ui::waypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moobot_ui::waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string way_point_name\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::moobot_ui::waypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moobot_ui::waypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.way_point_name);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct waypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moobot_ui::waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moobot_ui::waypoint_<ContainerAllocator>& v)
  {
    s << indent << "way_point_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.way_point_name);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOOBOT_UI_MESSAGE_WAYPOINT_H
