(cl:defpackage moobot_msgs-msg
  (:use )
  (:export
   "<SENSORSTATE>"
   "SENSORSTATE"
   "<BMS_STATUS>"
   "BMS_STATUS"
   "<CONVEYOR_STATUS>"
   "CONVEYOR_STATUS"
   "<LIFT_STATUS>"
   "LIFT_STATUS"
   "<MOOBOT_SCANNER>"
   "MOOBOT_SCANNER"
   "<MOOBOT_SENSOR_STATUS>"
   "MOOBOT_SENSOR_STATUS"
   "<MOOBOT_STATUS>"
   "MOOBOT_STATUS"
   "<PLC_DATA>"
   "PLC_DATA"
   "<ULTRASONIC_STATUS>"
   "ULTRASONIC_STATUS"
  ))

