# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from moobot_msgs/moobot_scanner.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class moobot_scanner(genpy.Message):
  _md5sum = "b971113dac55cb95f6b07a91c6331c49"
  _type = "moobot_msgs/moobot_scanner"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """byte fs_ossd
byte fs_w1
byte fs_w2
byte bs_ossd
byte bs_w1
byte bs_w2"""
  __slots__ = ['fs_ossd','fs_w1','fs_w2','bs_ossd','bs_w1','bs_w2']
  _slot_types = ['byte','byte','byte','byte','byte','byte']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       fs_ossd,fs_w1,fs_w2,bs_ossd,bs_w1,bs_w2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(moobot_scanner, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.fs_ossd is None:
        self.fs_ossd = 0
      if self.fs_w1 is None:
        self.fs_w1 = 0
      if self.fs_w2 is None:
        self.fs_w2 = 0
      if self.bs_ossd is None:
        self.bs_ossd = 0
      if self.bs_w1 is None:
        self.bs_w1 = 0
      if self.bs_w2 is None:
        self.bs_w2 = 0
    else:
      self.fs_ossd = 0
      self.fs_w1 = 0
      self.fs_w2 = 0
      self.bs_ossd = 0
      self.bs_w1 = 0
      self.bs_w2 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6b().pack(_x.fs_ossd, _x.fs_w1, _x.fs_w2, _x.bs_ossd, _x.bs_w1, _x.bs_w2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.fs_ossd, _x.fs_w1, _x.fs_w2, _x.bs_ossd, _x.bs_w1, _x.bs_w2,) = _get_struct_6b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6b().pack(_x.fs_ossd, _x.fs_w1, _x.fs_w2, _x.bs_ossd, _x.bs_w1, _x.bs_w2))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.fs_ossd, _x.fs_w1, _x.fs_w2, _x.bs_ossd, _x.bs_w1, _x.bs_w2,) = _get_struct_6b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6b = None
def _get_struct_6b():
    global _struct_6b
    if _struct_6b is None:
        _struct_6b = struct.Struct("<6b")
    return _struct_6b
