scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_link
    min_x: -0.85 #-0.575
    max_x: 0.85 # 0.575
    min_y: -0.85 #-0.735
    max_y: 0.85 #0.735
    min_z: -1.0
    max_z: 1.0
