// Generated by gencpp from file moobot_ui/station.msg
// DO NOT EDIT!


#ifndef MOOBOT_UI_MESSAGE_STATION_H
#define MOOBOT_UI_MESSAGE_STATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moobot_ui
{
template <class ContainerAllocator>
struct station_
{
  typedef station_<ContainerAllocator> Type;

  station_()
    : station_number(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  station_(const ContainerAllocator& _alloc)
    : station_number(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _station_number_type;
  _station_number_type station_number;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::moobot_ui::station_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moobot_ui::station_<ContainerAllocator> const> ConstPtr;

}; // struct station_

typedef ::moobot_ui::station_<std::allocator<void> > station;

typedef boost::shared_ptr< ::moobot_ui::station > stationPtr;
typedef boost::shared_ptr< ::moobot_ui::station const> stationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moobot_ui::station_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moobot_ui::station_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moobot_ui::station_<ContainerAllocator1> & lhs, const ::moobot_ui::station_<ContainerAllocator2> & rhs)
{
  return lhs.station_number == rhs.station_number &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moobot_ui::station_<ContainerAllocator1> & lhs, const ::moobot_ui::station_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moobot_ui

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moobot_ui::station_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moobot_ui::station_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moobot_ui::station_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moobot_ui::station_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moobot_ui::station_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moobot_ui::station_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moobot_ui::station_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c4f6212c6e666a3f4185ee1f58383a2";
  }

  static const char* value(const ::moobot_ui::station_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c4f6212c6e666a3ULL;
  static const uint64_t static_value2 = 0xf4185ee1f58383a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::moobot_ui::station_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moobot_ui/station";
  }

  static const char* value(const ::moobot_ui::station_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moobot_ui::station_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 station_number\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::moobot_ui::station_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moobot_ui::station_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.station_number);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct station_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moobot_ui::station_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moobot_ui::station_<ContainerAllocator>& v)
  {
    s << indent << "station_number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.station_number);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOOBOT_UI_MESSAGE_STATION_H
