stamped: false
inputs:
  linear:
    x: axis_left_y + button_dpad_up / 10 - button_dpad_down / 10
    y: axis_left_x
    z: axis_r2 - axis_l2
  angular:
    x: -axis_right_x
    y: axis_right_y
    z: button_l1 / 3 - button_r1 / 3 + axis_left_x
scales:
  linear:
    # Default scale is 1.0
    x: 0.6
    y: 0.0
    z: 0.0
  angular:
    x: 0.0
    y: 0.0
    z: 0.3
