# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from moobot_msgs/bms_status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class bms_status(genpy.Message):
  _md5sum = "3113256c57eafd1210064dbad908f61d"
  _type = "moobot_msgs/bms_status"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 battery_volt_1
float32 battery_volt_2
float32 battery_volt_total
float32 battery_temp_1
float32 battery_temp_2
float32 current_main
float32 total_power_wh
"""
  __slots__ = ['battery_volt_1','battery_volt_2','battery_volt_total','battery_temp_1','battery_temp_2','current_main','total_power_wh']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       battery_volt_1,battery_volt_2,battery_volt_total,battery_temp_1,battery_temp_2,current_main,total_power_wh

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(bms_status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.battery_volt_1 is None:
        self.battery_volt_1 = 0.
      if self.battery_volt_2 is None:
        self.battery_volt_2 = 0.
      if self.battery_volt_total is None:
        self.battery_volt_total = 0.
      if self.battery_temp_1 is None:
        self.battery_temp_1 = 0.
      if self.battery_temp_2 is None:
        self.battery_temp_2 = 0.
      if self.current_main is None:
        self.current_main = 0.
      if self.total_power_wh is None:
        self.total_power_wh = 0.
    else:
      self.battery_volt_1 = 0.
      self.battery_volt_2 = 0.
      self.battery_volt_total = 0.
      self.battery_temp_1 = 0.
      self.battery_temp_2 = 0.
      self.current_main = 0.
      self.total_power_wh = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.battery_volt_1, _x.battery_volt_2, _x.battery_volt_total, _x.battery_temp_1, _x.battery_temp_2, _x.current_main, _x.total_power_wh))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.battery_volt_1, _x.battery_volt_2, _x.battery_volt_total, _x.battery_temp_1, _x.battery_temp_2, _x.current_main, _x.total_power_wh,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.battery_volt_1, _x.battery_volt_2, _x.battery_volt_total, _x.battery_temp_1, _x.battery_temp_2, _x.current_main, _x.total_power_wh))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.battery_volt_1, _x.battery_volt_2, _x.battery_volt_total, _x.battery_temp_1, _x.battery_temp_2, _x.current_main, _x.total_power_wh,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
