# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from moobot_msgs/moobot_status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class moobot_status(genpy.Message):
  _md5sum = "6ac369f66a5b4dcf60abbe45c6d5c34f"
  _type = "moobot_msgs/moobot_status"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 agv_mode
bool agv_stopped
bool emergency
bool fault
string job"""
  __slots__ = ['agv_mode','agv_stopped','emergency','fault','job']
  _slot_types = ['int32','bool','bool','bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       agv_mode,agv_stopped,emergency,fault,job

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(moobot_status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.agv_mode is None:
        self.agv_mode = 0
      if self.agv_stopped is None:
        self.agv_stopped = False
      if self.emergency is None:
        self.emergency = False
      if self.fault is None:
        self.fault = False
      if self.job is None:
        self.job = ''
    else:
      self.agv_mode = 0
      self.agv_stopped = False
      self.emergency = False
      self.fault = False
      self.job = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i3B().pack(_x.agv_mode, _x.agv_stopped, _x.emergency, _x.fault))
      _x = self.job
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.agv_mode, _x.agv_stopped, _x.emergency, _x.fault,) = _get_struct_i3B().unpack(str[start:end])
      self.agv_stopped = bool(self.agv_stopped)
      self.emergency = bool(self.emergency)
      self.fault = bool(self.fault)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.job = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.job = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i3B().pack(_x.agv_mode, _x.agv_stopped, _x.emergency, _x.fault))
      _x = self.job
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 7
      (_x.agv_mode, _x.agv_stopped, _x.emergency, _x.fault,) = _get_struct_i3B().unpack(str[start:end])
      self.agv_stopped = bool(self.agv_stopped)
      self.emergency = bool(self.emergency)
      self.fault = bool(self.fault)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.job = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.job = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i3B = None
def _get_struct_i3B():
    global _struct_i3B
    if _struct_i3B is None:
        _struct_i3B = struct.Struct("<i3B")
    return _struct_i3B
