// Generated by gencpp from file moobot_ui/pid_msg.msg
// DO NOT EDIT!


#ifndef MOOBOT_UI_MESSAGE_PID_MSG_H
#define MOOBOT_UI_MESSAGE_PID_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace moobot_ui
{
template <class ContainerAllocator>
struct pid_msg_
{
  typedef pid_msg_<ContainerAllocator> Type;

  pid_msg_()
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)  {
    }
  pid_msg_(const ContainerAllocator& _alloc)
    : kp(0.0)
    , ki(0.0)
    , kd(0.0)  {
  (void)_alloc;
    }



   typedef float _kp_type;
  _kp_type kp;

   typedef float _ki_type;
  _ki_type ki;

   typedef float _kd_type;
  _kd_type kd;





  typedef boost::shared_ptr< ::moobot_ui::pid_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moobot_ui::pid_msg_<ContainerAllocator> const> ConstPtr;

}; // struct pid_msg_

typedef ::moobot_ui::pid_msg_<std::allocator<void> > pid_msg;

typedef boost::shared_ptr< ::moobot_ui::pid_msg > pid_msgPtr;
typedef boost::shared_ptr< ::moobot_ui::pid_msg const> pid_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moobot_ui::pid_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moobot_ui::pid_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::moobot_ui::pid_msg_<ContainerAllocator1> & lhs, const ::moobot_ui::pid_msg_<ContainerAllocator2> & rhs)
{
  return lhs.kp == rhs.kp &&
    lhs.ki == rhs.ki &&
    lhs.kd == rhs.kd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::moobot_ui::pid_msg_<ContainerAllocator1> & lhs, const ::moobot_ui::pid_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace moobot_ui

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::moobot_ui::pid_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moobot_ui::pid_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moobot_ui::pid_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moobot_ui::pid_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moobot_ui::pid_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moobot_ui::pid_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moobot_ui::pid_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "08d0ca1f582560895ecba909de1d88ec";
  }

  static const char* value(const ::moobot_ui::pid_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x08d0ca1f58256089ULL;
  static const uint64_t static_value2 = 0x5ecba909de1d88ecULL;
};

template<class ContainerAllocator>
struct DataType< ::moobot_ui::pid_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moobot_ui/pid_msg";
  }

  static const char* value(const ::moobot_ui::pid_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moobot_ui::pid_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 kp\n"
"float32 ki\n"
"float32 kd\n"
;
  }

  static const char* value(const ::moobot_ui::pid_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moobot_ui::pid_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp);
      stream.next(m.ki);
      stream.next(m.kd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pid_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moobot_ui::pid_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moobot_ui::pid_msg_<ContainerAllocator>& v)
  {
    s << indent << "kp: ";
    Printer<float>::stream(s, indent + "  ", v.kp);
    s << indent << "ki: ";
    Printer<float>::stream(s, indent + "  ", v.ki);
    s << indent << "kd: ";
    Printer<float>::stream(s, indent + "  ", v.kd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOOBOT_UI_MESSAGE_PID_MSG_H
