// Generated by gencpp from file agv_mode_srvs/agv_mode_srv.msg
// DO NOT EDIT!


#ifndef AGV_MODE_SRVS_MESSAGE_AGV_MODE_SRV_H
#define AGV_MODE_SRVS_MESSAGE_AGV_MODE_SRV_H

#include <ros/service_traits.h>


#include <agv_mode_srvs/agv_mode_srvRequest.h>
#include <agv_mode_srvs/agv_mode_srvResponse.h>


namespace agv_mode_srvs
{

struct agv_mode_srv
{

typedef agv_mode_srvRequest Request;
typedef agv_mode_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct agv_mode_srv
} // namespace agv_mode_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agv_mode_srvs::agv_mode_srv > {
  static const char* value()
  {
    return "ae96190e987c19063498c13c3886f347";
  }

  static const char* value(const ::agv_mode_srvs::agv_mode_srv&) { return value(); }
};

template<>
struct DataType< ::agv_mode_srvs::agv_mode_srv > {
  static const char* value()
  {
    return "agv_mode_srvs/agv_mode_srv";
  }

  static const char* value(const ::agv_mode_srvs::agv_mode_srv&) { return value(); }
};


// service_traits::MD5Sum< ::agv_mode_srvs::agv_mode_srvRequest> should match
// service_traits::MD5Sum< ::agv_mode_srvs::agv_mode_srv >
template<>
struct MD5Sum< ::agv_mode_srvs::agv_mode_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agv_mode_srvs::agv_mode_srv >::value();
  }
  static const char* value(const ::agv_mode_srvs::agv_mode_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_mode_srvs::agv_mode_srvRequest> should match
// service_traits::DataType< ::agv_mode_srvs::agv_mode_srv >
template<>
struct DataType< ::agv_mode_srvs::agv_mode_srvRequest>
{
  static const char* value()
  {
    return DataType< ::agv_mode_srvs::agv_mode_srv >::value();
  }
  static const char* value(const ::agv_mode_srvs::agv_mode_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agv_mode_srvs::agv_mode_srvResponse> should match
// service_traits::MD5Sum< ::agv_mode_srvs::agv_mode_srv >
template<>
struct MD5Sum< ::agv_mode_srvs::agv_mode_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agv_mode_srvs::agv_mode_srv >::value();
  }
  static const char* value(const ::agv_mode_srvs::agv_mode_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agv_mode_srvs::agv_mode_srvResponse> should match
// service_traits::DataType< ::agv_mode_srvs::agv_mode_srv >
template<>
struct DataType< ::agv_mode_srvs::agv_mode_srvResponse>
{
  static const char* value()
  {
    return DataType< ::agv_mode_srvs::agv_mode_srv >::value();
  }
  static const char* value(const ::agv_mode_srvs::agv_mode_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGV_MODE_SRVS_MESSAGE_AGV_MODE_SRV_H
